name: EEX Scraper Scheduled

on:
  schedule:
    # 09h00 France (UTC+1 → 08h UTC)
    - cron: '0 8 * * 1-5'

    # 18h00 France (UTC+1 → 17h UTC)
    - cron: '32 17 * * 1-5'

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      GitHub__Token: ${{ secrets.EEX_WEBSCRAPING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run
        run: dotnet run --project WebScrapingHub/WebScrapingHub.csproj --configuration Release
