name: EEX Scraper Scheduled

on:
  schedule:
    # Toutes les 30 minutes, lundi-vendredi, de 08h à 18h Paris environ
    - cron: '*/30 6-16 * * 1-5'

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      GitHub__Token: ${{ secrets.EEX_WEBSCRAPING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run scraper
        run: dotnet run --project WebScrapingHub/WebScrapingHub.csproj --configuration Release
